name = "cf-worker-template"
type = "javascript"
zone_id = ""
account_id = "94b7cce949e7c369b336bdb06f38f9ad"
route = ""
workers_dev = true

[build]
command = "yarn && yarn build"

[build.upload]
format = "modules"
dir = "dist"
main = "./index.mjs"
